version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - app-network
    links:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network
  client:
    build: './client'
    volumes:
      - './client:/home/node/app'
    working_dir: '/home/node/app'
    command: 'yarn start'
    ports: 
      - 3001:3000
networks:
  app-network:
    driver: bridge
